from app.models import LocalEvent, SourceReference

SAMPLE_EVENTS = [
    LocalEvent(
        id="fuji-shibazakura-festival",
        spot_id="fuji-shibazakura",
        name="富士芝桜まつり",
        region="富士五湖・山梨",
        description="富士山を背景に、春色の芝桜が一面に広がる花の季節。",
        image_url="/sample-media/fuji-spring.svg",
        start_month=4,
        end_month=5,
        best_time="4月中旬〜5月下旬",
        category="花の絶景",
    ),
    LocalEvent(
        id="gion-matsuri",
        spot_id="kyoto-kamogawa",
        name="祇園祭",
        region="京都市・京都",
        description="7月に行われる京都の祭礼。京都観光公式案内では神幸祭を7月17日、還幸祭を7月24日と案内しています。",
        image_url="/sample-media/gion-lanterns.svg",
        start_month=7,
        end_month=7,
        best_time="7月",
        category="夏祭り",
        data_status="sourced",
        sources=[
            SourceReference(
                publisher="Kyoto Travel",
                title="Gion Matsuri Festival",
                url="https://kyoto.travel/en/travel-inspiration/gion-matsuri-festival/",
                verified_fields=["description", "start_month", "end_month", "best_time"],
            )
        ],
    ),
    LocalEvent(
        id="nara-toka-e",
        spot_id="nara-park",
        name="なら燈花会",
        region="奈良公園・奈良",
        description="夏の夜、奈良公園一帯にろうそくの灯りがともる催し。",
        image_url="/sample-media/toka-e-lanterns.svg",
        start_month=8,
        end_month=8,
        best_time="8月上旬〜中旬",
        category="夏の夜",
    ),
    LocalEvent(
        id="shiretoko-drift-ice",
        spot_id="shiretoko",
        name="知床流氷シーズン",
        region="知床・北海道",
        description="オホーツク海を白く染める流氷と、冬の野生動物に出会う季節。",
        image_url="/sample-media/drift-ice.svg",
        start_month=2,
        end_month=3,
        best_time="2月〜3月",
        category="冬の自然",
    ),
]
