from app.models import MemoryPhoto, MemoryCoordinate, TravelMemory

SAMPLE_MEMORIES = [
    TravelMemory(
        id="kyoto-autumn-evening",
        title="川風にほどけた、京都の秋",
        region="京都・奈良",
        visited_at="2025-11-18",
        note="夕暮れの鴨川から、灯りのともる奈良公園まで。歩いた時間ごと残した小さな旅。",
        route=[
            MemoryCoordinate(
                spot_id="kyoto-kamogawa",
                label="鴨川の夕暮れ",
                latitude=35.0116,
                longitude=135.7681,
            ),
            MemoryCoordinate(
                spot_id="nara-park",
                label="奈良公園",
                latitude=34.6851,
                longitude=135.8048,
            ),
            MemoryCoordinate(
                spot_id="ine",
                label="伊根の舟屋",
                latitude=35.674,
                longitude=135.286,
            ),
        ],
        photos=[
            MemoryPhoto(
                id="kyoto-memory-river",
                image_url="/sample-media/kyoto-river.svg",
                caption="水面に夕焼けが映った、旅のはじまり",
                captured_at="2025-11-18T16:42:00+09:00",
                latitude=35.0118,
                longitude=135.7684,
                spot_id="kyoto-kamogawa",
            ),
            MemoryPhoto(
                id="kyoto-memory-deer",
                image_url="/sample-media/nara-grove.svg",
                caption="木立の向こうで、鹿と目が合った",
                captured_at="2025-11-18T18:16:00+09:00",
                latitude=34.6854,
                longitude=135.8051,
                spot_id="nara-park",
            ),
            MemoryPhoto(
                id="kyoto-memory-lantern",
                image_url="/sample-media/ine-bay.svg",
                caption="帰り道に見つけた、静かな灯り",
                captured_at="2025-11-18T19:03:00+09:00",
                latitude=35.6738,
                longitude=135.2864,
                spot_id="ine",
            ),
        ],
    ),
    TravelMemory(
        id="yakushima-green-morning",
        title="雨あがり、苔の森を歩いた朝",
        region="屋久島・鹿児島",
        visited_at="2024-06-09",
        note="雨粒が残る森の音を聞きながら、ゆっくり歩いた一日の記録。",
        route=[
            MemoryCoordinate(
                spot_id="yakushima",
                label="屋久島の苔の森",
                latitude=30.358,
                longitude=130.523,
            ),
        ],
        photos=[
            MemoryPhoto(
                id="yakushima-memory-moss",
                image_url="/sample-media/moss-forest.svg",
                caption="雨のあと、森の緑がいちばん深くなる",
                captured_at="2024-06-09T09:27:00+09:00",
                latitude=30.359,
                longitude=130.524,
                spot_id="yakushima",
            ),
            MemoryPhoto(
                id="yakushima-memory-path",
                image_url="/sample-media/moss-forest.svg",
                caption="足音まで吸い込まれる、苔むした小径",
                captured_at="2024-06-09T10:51:00+09:00",
                latitude=30.356,
                longitude=130.521,
                spot_id="yakushima",
            ),
        ],
    ),
]
