from app.models import Spot

SAMPLE_MODE = True

SPOTS = [
    Spot(
        id="yakushima",
        region="Yakushima, Kagoshima",
        prefecture="鹿児島県",
        title="雨の森に、苔が息づく。もののけの島へ",
        description="樹齢数千年の杉と、しっとり光る苔の森。雨音まで好きになる、屋久島の朝。",
        image_url="https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=85",
        category="秘境",
        local_food="首折れサバのお刺身",
        local_species="ヤクシカ",
        latitude=30.358,
        longitude=130.523,
        tags=["世界自然遺産", "苔の森", "離島"],
        creator="旅と、余白",
        likes=2400,
        local_trivia="雨の多い屋久島では、森の苔が雨粒を受け止めて、晴れた後もしっとりした緑が続きます。",
        is_world_heritage=True,
        heritage_name="屋久島",
    ),
    Spot(
        id="shiretoko",
        region="Shiretoko, Hokkaido",
        prefecture="北海道",
        title="流氷の向こうに、オオワシが舞う冬",
        description="知床の海を埋め尽くす流氷と、空をゆくオオワシ。ここでしか見られない冬の景色。",
        image_url="https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1600&q=85",
        category="野生のいきもの",
        local_food="知床の天然エゾバフンウニ",
        local_species="オオワシ",
        latitude=44.076,
        longitude=145.098,
        tags=["流氷", "野生動物", "冬の絶景"],
        creator="北のさんぽ道",
        likes=1800,
        local_trivia="知床の流氷は、遠くのアムール川から運ばれてくる植物プランクトンが豊かな海の始まりです。",
        is_world_heritage=True,
        heritage_name="知床",
    ),
    Spot(
        id="shiretoko-five-lakes",
        region="Shiretoko Five Lakes, Hokkaido",
        prefecture="北海道",
        title="森に映る五つの湖、静かな知床の朝",
        description="原生林に囲まれた湖面に、知床連山が映り込む。木道を歩いて出会う世界自然遺産の風景。",
        image_url="https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=85",
        category="世界遺産",
        local_food="知床の鮭とば",
        local_species="エゾシカ",
        latitude=44.122,
        longitude=145.087,
        tags=["五つの湖", "原生林", "知床"],
        creator="北のさんぽ道",
        likes=1600,
        local_trivia="知床五湖には、ヒグマ活動期に専門ガイド同行が必要な地上遊歩道と、高架木道の2つの歩き方があります。",
        is_world_heritage=True,
        heritage_name="知床",
    ),
    Spot(
        id="ine",
        region="Ine, Kyoto",
        prefecture="京都府",
        title="舟屋の窓を開けたら、海だった。",
        description="海と暮らしがひと続きになる伊根の朝。舟屋の並ぶ湾を、小さな船が静かに進みます。",
        image_url="https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1600&q=85",
        category="海辺のまち",
        local_food="伊根のぶりしゃぶ",
        local_species="伊根湾のマダイ",
        latitude=35.674,
        longitude=135.286,
        tags=["舟屋", "漁師町", "海の京都"],
        creator="水辺の暮らし",
        likes=3200,
        local_trivia="伊根の舟屋は、1階が船のガレージ、2階が住まいという海と暮らす独特のつくりです。",
    ),
    Spot(
        id="kyoto-kamogawa",
        region="Kyoto City, Kyoto",
        prefecture="京都府",
        title="川のせせらぎと、夕暮れの鴨川さんぽ",
        description="街の真ん中なのに、川風が気持ちいい。鴨川べりの夕暮れは、京都の日常にまざる小さな寄り道。",
        image_url="https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1600&q=85",
        category="まち歩き",
        local_food="にしんそば",
        local_species="鴨川のカワセミ",
        latitude=35.0116,
        longitude=135.7681,
        tags=["鴨川", "夕暮れ", "街さんぽ"],
        creator="京都、いつもの道",
        likes=2100,
        local_trivia="鴨川沿いの納涼床は、夏の京都で川風を感じながら食事を楽しむ季節限定の風物詩です。",
    ),
    Spot(
        id="nara-park",
        region="Nara Park, Nara",
        prefecture="奈良県",
        title="木漏れ日の先に、鹿と目が合う。",
        description="朝の奈良公園をゆっくり歩くと、木立の向こうに鹿の姿。古都の森で深呼吸するひととき。",
        image_url="https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=85",
        category="野生のいきもの",
        local_food="柿の葉寿司",
        local_species="奈良公園のシカ",
        latitude=34.6851,
        longitude=135.8048,
        tags=["古都の森", "鹿に会える", "朝さんぽ"],
        creator="古都のよりみち",
        likes=2700,
        local_trivia="奈良公園の鹿は、春日大社の神様の使いとして大切にされてきたと伝えられています。",
        is_world_heritage=True,
        heritage_name="古都奈良の文化財",
    ),
    Spot(
        id="fuji-shibazakura",
        region="Fuji Five Lakes, Yamanashi",
        prefecture="山梨県",
        title="富士山のふもと、ピンクの花のじゅうたん",
        description="春の富士を彩る芝桜。花の向こうに富士山が顔を出す、季節限定の景色です。",
        image_url="https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1600&q=85",
        video_url="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
        category="季節の絶景",
        local_food="吉田のうどん",
        local_species="富士の芝桜",
        latitude=35.455,
        longitude=138.617,
        tags=["春だけ", "富士山", "花の絶景"],
        creator="花と山の記録",
        likes=5100,
        local_trivia="富士山を背景に咲く芝桜は、例年4月中旬から5月下旬ごろに見頃を迎える春の景色です。",
    ),
    Spot(
        id="takachiho",
        region="Takachiho, Miyazaki",
        prefecture="宮崎県",
        title="水しぶきの先に、神話の渓谷",
        description="柱状節理の岩肌を縫う真名井の滝。朝の光が差し込む時間は、思わず息をのむ美しさ。",
        image_url="https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=85",
        category="秘境",
        local_food="高千穂牛の炭火焼き",
        local_species="ヤマメ",
        latitude=32.711,
        longitude=131.307,
        tags=["渓谷", "神話の里", "朝の景色"],
        creator="九州、深呼吸",
        likes=2900,
        local_trivia="高千穂峡の岩肌に見える柱状の模様は、火砕流が冷えて固まるときにできたものです。",
    ),
]
